name: Lambda Triggered Workflow
on:
  repository_dispatch:
    types: "my-event"  # Change this to match your event type

jobs:
  monitor-s3-events:
    runs-on: ubuntu-latest
    environment: s3 trigger
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIA3IDLKAAK7XN6AU6W
          aws-secret-access-key: D9xj4kSWSZlYu1L+Ruqzc7wpEDZmf85SYkYIFYXe
          aws-region: us-east-1
        
      - name: List S3 Objects
        run: |
          # Use AWS CLI command to list all files and folders in the S3 bucket
          echo "Listing all files and folders in the S3 bucket..."
          aws s3 ls s3://s3-hf-auto --recursive
