name: Lambda Triggered Workflow
on:
  repository_dispatch:
    types: "my-event"  # Change this to match your event type

jobs:
  monitor-s3-events:
    runs-on: ubuntu-latest
    # permissions:
    #   id-token: write
    #   contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      # - name: Set up AWS CLI
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: arn:aws:iam::773319163925:role/s3_trigger
      #     aws-region: us-east-1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id : ASIA3IDLKAAK4SUXYBSA
          aws_secret_access_key : FHg+4NhEjfSvg4uSjPBDEQA7fZPLTFyMDUPROn41
          aws_session_token : IQoJb3JpZ2luX2VjECoaCXVzLWVhc3QtMSJHMEUCIQDdRbKv9JB95GmaJqzfVc+P4Wfhs6O+BNR0otFZjyldsAIgb3hA7agAAzIzGJV+5vz4oIIGte79aS2qOsTsXXOw3iYqhgMIcxAAGgw3NzMzMTkxNjM5MjUiDAHqn2sXN5L3dq0kjCrjAsMwIfKZYRMba4zoWmazsA7W3f19Jw4zi6aXykshA2DP2DQ32nX17gs/cizDco3mlHzm0SqhoGo72XGhXg4Jlow58yOq1VLHy87XT3gBdzpq49xuHJEDXgzK1rlP8b25fCEdKlQ/VZM0IGnDZk5D4n/JDDZD5XzI+C+2x7gJCn5+kfsK0ecQ81MKjyYG3LNWLeKI3LdzvfG9IvBi6lweTUoMTNyf7T7bq7syo/mBWtk0DJwzHeGKZA0UHPxLzUTgi2da0IXUFyU50cIw1TfvOIm0S6w70jbFFVKlqRe8wheAa72Sr/dhm4+KsBMgPdZg/HpyylicujSHFQecjqndbmin7XvJWbjCe5282sUD8RBWHCjYSPPj+QMQJ5jgFoW9AAne3LxIOjYXv85PpoUblFb2Kh6IBbbAOIjSNvcJWO3wUiYlNhZFZ2VdMCIQXccxRL3uA8SCiwaRm6cqERb7DmQpIfwwxqrSqgY6pgFuQfkjNBe63ilA6eg2FaQdfaZBzavPJ85/FpXJefq5FQY7kVclcnwjEhUDoY0WLH/74MHle+zn1i0A5LzRsJnW6XzrWyeFYUgDabKV+OpnvKC5zdgUAfcwIsk81QuOTt0ssfuVYw14a17zV+gGEDmG+AC4WceNts/GgKbsZ/9EFGk6KnWgs3ys+bWBPP6Dc3G09mkRukGB7M8KLvi3GlQt68fjq5rN
          aws-region: us-east-1
        
      - name: List S3 Objects
        run: |
          # Use AWS CLI command to list all files and folders in the S3 bucket
          echo "Listing all files and folders in the S3 bucket..."
          aws s3 ls s3://s3-hf-auto --recursive
